import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Property, Vendor, Tenant } from '@/types';

interface ExportOptions {
  property: Property;
  vendors: Vendor[];
  tenants: Tenant[];
  companyName?: string;
}

function statusLabel(status: string): string {
  switch (status) {
    case 'compliant': return 'Compliant';
    case 'non-compliant': return 'Non-Compliant';
    case 'expiring': return 'Expiring';
    case 'expired': return 'Expired';
    default: return status;
  }
}

export function exportComplianceReport({ property, vendors, tenants, companyName }: ExportOptions): void {
  const doc = new jsPDF();
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Compliance Report', 14, 22);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  if (companyName) doc.text(companyName, 14, 30);
  doc.text(`Report Date: ${dateStr}`, 14, companyName ? 36 : 30);

  // Property info
  let y = companyName ? 46 : 40;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text(property.name, 14, y);
  if (property.address) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    y += 6;
    doc.text(property.address, 14, y);
  }

  // Summary section
  y += 12;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Summary', 14, y);
  y += 8;

  const allEntities = [
    ...vendors.map((v) => v.status),
    ...tenants.map((t) => t.insurance_status),
  ];
  const total = allEntities.length;
  const compliantCount = allEntities.filter((s) => s === 'compliant').length;
  const nonCompliantCount = allEntities.filter((s) => s === 'non-compliant').length;
  const expiringCount = allEntities.filter((s) => s === 'expiring').length;
  const expiredCount = allEntities.filter((s) => s === 'expired').length;
  const complianceRate = total > 0 ? Math.round((compliantCount / total) * 100) : 0;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const summaryLines = [
    `Overall Compliance: ${complianceRate}%`,
    `Total Entities: ${total} (${vendors.length} vendors, ${tenants.length} tenants)`,
    `Compliant: ${compliantCount} | Non-Compliant: ${nonCompliantCount} | Expiring: ${expiringCount} | Expired: ${expiredCount}`,
  ];
  for (const line of summaryLines) {
    doc.text(line, 14, y);
    y += 6;
  }

  // Vendor section
  if (vendors.length > 0) {
    y += 6;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Vendors', 14, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      head: [['Name', 'Status', 'Expiration', 'Coverage Types']],
      body: vendors.map((v) => [
        v.name,
        statusLabel(v.status),
        v.expiration_date ? new Date(v.expiration_date).toLocaleDateString('en-US') : 'N/A',
        (Array.isArray(v.coverage) ? v.coverage.map((c: { type?: string }) => c.type).filter(Boolean).join(', ') : '') || 'N/A',
      ]),
      styles: { fontSize: 9 },
      headStyles: { fillColor: [41, 128, 185] },
      alternateRowStyles: { fillColor: [245, 245, 245] },
    });

    y = (doc as unknown as Record<string, { finalY: number }>).lastAutoTable?.finalY ?? y + 20;
  }

  // Tenant section
  if (tenants.length > 0) {
    y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
    y += 10;

    // Check if we need a new page
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Tenants', 14, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      head: [['Name', 'Unit', 'Status', 'Lease End']],
      body: tenants.map((t) => [
        t.name,
        t.unit ?? 'N/A',
        statusLabel(t.insurance_status),
        t.lease_end ? new Date(t.lease_end).toLocaleDateString('en-US') : 'N/A',
      ]),
      styles: { fontSize: 9 },
      headStyles: { fillColor: [41, 128, 185] },
      alternateRowStyles: { fillColor: [245, 245, 245] },
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150);
    doc.text(
      `Generated by SmartCOI — ${dateStr} ${timeStr}`,
      14,
      doc.internal.pageSize.height - 10
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 30,
      doc.internal.pageSize.height - 10
    );
  }

  // Download
  const safeName = property.name.replace(/[^a-zA-Z0-9]/g, '_');
  const dateSlug = now.toISOString().split('T')[0];
  doc.save(`${safeName}_Compliance_Report_${dateSlug}.pdf`);
}
