import type { PropertyType } from './types';

export const propertyTypes: PropertyType[] = [
  {
    slug: 'office-buildings',
    name: 'Office Building',
    plural: 'Office Buildings',
    description:
      'Class A, B, and C office properties including high-rises, suburban office parks, and mixed-use office spaces.',
    vendorExamples: ['janitorial services', 'HVAC contractors', 'elevator maintenance', 'security companies'],
    tenantExamples: ['law firms', 'tech companies', 'accounting firms', 'consulting agencies'],
    complianceChallenges:
      'Office buildings face uniquely high vendor turnover that makes COI tracking a constant challenge. Cleaning crews, IT contractors, HVAC technicians, and security teams rotate frequently — often with subcontractors that change quarterly. Each vendor swap means a new certificate to collect, verify, and file before the contractor sets foot on the property. Meanwhile, multi-tenant office buildings add another layer of complexity: a 20-story Class A tower might have 40+ tenants, each with a different lease requiring different coverage minimums. Law firms typically carry higher professional liability, while co-working operators need broader general liability. When a property manager is juggling renewals for dozens of vendors and tenants simultaneously, certificates inevitably slip through the cracks. A lapsed janitorial vendor policy might go unnoticed for months — until a slip-and-fall claim lands on the building owner\'s desk with no coverage to back it up. The financial exposure compounds quickly in office environments where foot traffic is high and common areas are shared across multiple tenants and their visitors.',
    commonCoverageGaps:
      'The most frequently missed gap in office buildings is additional insured endorsement verification. Vendors submit certificates listing adequate limits, but the actual endorsement naming the property owner is either missing or expired. Elevator maintenance contracts often lack the umbrella or excess liability needed to cover catastrophic injury claims. IT and low-voltage contractors are routinely allowed on-site without workers\' compensation verification, creating direct employer liability for the building owner. Tenant certificates frequently expire mid-lease with no follow-up process, and after-hours cleaning crews — among the highest-risk vendors for slip-and-fall incidents — are often the last to have their COIs checked.',
    howSmartCOIHelps:
      'SmartCOI\'s bulk upload processes dozens of office vendor and tenant COIs in minutes, while AI extraction automatically catches missing additional insured endorsements that manual review misses. Automated expiration alerts ensure no certificate lapses go unnoticed, and the self-service vendor portal lets contractors upload renewals directly — eliminating the back-and-forth email chains that slow down office property management teams.',
  },
  {
    slug: 'retail-centers',
    name: 'Retail Center',
    plural: 'Retail Centers',
    description:
      'Shopping centers, strip malls, power centers, and lifestyle centers with multiple retail tenants.',
    vendorExamples: ['parking lot maintenance', 'landscaping crews', 'snow removal', 'signage installers'],
    tenantExamples: ['restaurants', 'clothing retailers', 'fitness studios', 'salons'],
    complianceChallenges:
      'Retail centers present some of the most complex COI tracking challenges in commercial real estate because of the sheer diversity of tenant risk profiles under one roof. A single shopping center might house a full-service restaurant with liquor liability, a nail salon handling chemical products, a daycare center, and a big-box anchor tenant — each requiring fundamentally different coverage types and limits. Seasonal vendors add another unpredictable layer: holiday pop-up shops, parking lot carnival operators, Santa photo booth vendors, and food truck events all need short-term certificates that traditional tracking methods struggle to manage. The tenant mix also shifts more frequently than in office environments. Retail lease terms are shorter, and turnover during economic downturns can mean 15-20% of spaces changing hands annually. Each new tenant means a new COI to collect before build-out contractors arrive, and each departing tenant\'s coverage needs to remain active through lease expiration. Property managers at large retail centers often manage 50+ active certificates at any given time, with expiration dates scattered across every month of the year. Without a systematic tracking approach, compliance gaps become inevitable — and in a high-foot-traffic retail environment, those gaps represent significant slip-and-fall, product liability, and liquor liability exposure.',
    commonCoverageGaps:
      'Liquor liability is the single most dangerous gap in retail center compliance. Restaurant and bar tenants frequently carry general liability but lack the separate liquor liability endorsement required by most retail leases. Food court vendors and temporary food service operators often have inadequate product liability limits. Seasonal and pop-up tenants are routinely allowed to operate with no certificate on file at all, especially during high-pressure holiday periods when property managers prioritize occupancy over compliance. Parking lot maintenance vendors — responsible for the highest-traffic common areas — frequently lack adequate auto liability coverage for their equipment operations.',
    howSmartCOIHelps:
      'SmartCOI\'s AI extraction identifies coverage types like liquor liability and product liability automatically, flagging tenants who are missing required endorsements before they open for business. Compliance templates let retail property managers set different requirement profiles for restaurants, retail shops, and service tenants, while automated follow-up emails chase down renewals without manual effort.',
  },
  {
    slug: 'industrial-warehouses',
    name: 'Industrial Warehouse',
    plural: 'Industrial Warehouses',
    description:
      'Warehouses, distribution centers, flex spaces, and light manufacturing facilities.',
    vendorExamples: ['dock equipment repair', 'forklift maintenance', 'fire suppression contractors', 'roofing companies'],
    tenantExamples: ['logistics companies', 'e-commerce fulfillment', 'manufacturers', 'cold storage operators'],
    complianceChallenges:
      'Industrial warehouses operate in a higher-stakes insurance environment than most commercial property types. The combination of heavy equipment, hazardous materials, and physically demanding work means that coverage minimums are significantly higher — and the consequences of a compliance lapse are far more severe. A single forklift accident or chemical spill can generate claims in the millions, making it critical that every vendor and tenant maintains adequate coverage at all times. The challenge is compounded by the nature of industrial operations. Dock equipment repair crews, fire suppression contractors, and roofing companies often work on tight turnaround schedules, arriving on-site with little advance notice. Property managers rarely have time to manually verify certificates before work begins, so contractors frequently operate on expired or insufficient policies. Tenant operations add further complexity: a logistics company storing flammable goods requires environmental liability coverage, while a cold storage operator needs specialized equipment breakdown insurance. OSHA oversight in industrial settings means that compliance failures don\'t just create financial exposure — they can trigger regulatory penalties and facility shutdowns. Property managers who rely on spreadsheets or email-based tracking consistently find that industrial COI volumes and complexity outpace their manual processes within the first year of operations.',
    commonCoverageGaps:
      'Environmental and pollution liability is the most commonly missing coverage in industrial properties. Tenants handling chemicals, fuel, or hazardous waste frequently carry standard general liability without the pollution endorsement that industrial leases require. Workers\' compensation gaps are particularly dangerous in warehouse environments — subcontractors performing physical labor without active workers\' comp coverage expose the property owner to direct liability for on-site injuries. Equipment breakdown and inland marine coverage for high-value machinery is often overlooked during lease negotiations. Auto liability limits for tenants operating truck fleets from the property are frequently below the $2M+ minimums that industrial leases should require.',
    howSmartCOIHelps:
      'SmartCOI extracts coverage limits, endorsements, and policy dates from industrial COIs automatically — including umbrella and excess liability policies that are standard in warehouse environments. Industry-specific compliance templates set the higher minimums that industrial properties require, and real-time compliance dashboards give property managers instant visibility into which tenants and vendors have gaps before an OSHA inspection or incident occurs.',
  },
  {
    slug: 'multifamily-apartments',
    name: 'Multifamily Apartment',
    plural: 'Multifamily Apartments',
    description:
      'Apartment complexes, garden-style communities, mid-rise and high-rise residential buildings.',
    vendorExamples: ['plumbing contractors', 'pest control', 'pool maintenance', 'painting companies'],
    tenantExamples: ['individual residents', 'corporate housing tenants', 'student housing residents'],
    complianceChallenges:
      'Multifamily apartments generate the highest volume of insurance certificates of any property type, driven by constant resident turnover and a steady rotation of maintenance vendors. A 200-unit apartment complex might process 60-80 move-ins per year, each requiring a renters insurance certificate before key handoff. Unlike commercial tenants who have dedicated risk managers, individual residents often purchase the cheapest renters policy available, let it lapse after a few months, or name the wrong entity as additional insured. Tracking these certificates manually becomes a full-time job that most property management teams simply cannot sustain. On the vendor side, multifamily properties rely on a broad mix of contractors — plumbers, electricians, pest control, pool maintenance, painters, landscapers, and turnover cleaning crews — many of whom are small businesses with inconsistent insurance practices. Move-in and move-out periods create surge demand for vendors, with multiple contractors on-site simultaneously during peak turnover months. The combination of high resident volume and vendor diversity means that multifamily property managers often manage 200+ active certificates, with dozens expiring every month. A single water damage claim from an uninsured resident or an injury from an uninsured pool contractor can cost more than years of insurance tracking would have prevented.',
    commonCoverageGaps:
      'Renters insurance lapse rates are the defining compliance challenge for multifamily properties. Studies show that 30-40% of residents who purchase renters insurance at move-in allow their policies to lapse within six months, leaving the property owner exposed to subrogation claims for water damage, fire, and liability incidents. Pool and amenity maintenance vendors frequently carry general liability but lack the specific additional insured endorsement naming the property. Turnover vendors — painters, cleaners, and carpet installers — are often hired on short notice without any COI verification. Landscaping crews operating heavy mowers and trimmers rarely carry adequate auto liability for their equipment trailers.',
    howSmartCOIHelps:
      'SmartCOI automates the high-volume certificate tracking that multifamily properties demand. Bulk upload handles dozens of renters insurance certificates at once, AI extraction verifies that residents named the correct additional insured, and automated expiration alerts catch lapsed policies before they create exposure. The vendor portal lets maintenance contractors submit renewals on their own schedule, reducing the administrative burden on leasing office staff.',
  },
  {
    slug: 'mixed-use-properties',
    name: 'Mixed-Use Property',
    plural: 'Mixed-Use Properties',
    description:
      'Properties combining retail, office, and residential uses — often with ground-floor commercial and upper-floor residential.',
    vendorExamples: ['general contractors', 'fire safety inspectors', 'waste management', 'window cleaning'],
    tenantExamples: ['ground-floor restaurants', 'professional offices', 'residential tenants', 'co-working spaces'],
    complianceChallenges:
      'Mixed-use properties combine the compliance headaches of every other property type into a single building. A typical mixed-use development might have ground-floor retail tenants, mid-level office space, and upper-floor residential units — each governed by different lease structures, different coverage requirements, and different regulatory standards. The property manager must simultaneously enforce commercial general liability minimums for a restaurant tenant, professional liability requirements for a law office, and renters insurance obligations for 50 residential units, all within the same property. Vendors add another dimension of complexity. A window cleaning crew servicing the entire building needs coverage that satisfies the highest requirement tier across all use types, but many vendors carry only the minimum required by their primary contract. Shared infrastructure — HVAC systems, elevators, parking structures, fire suppression — creates overlapping liability zones where it is unclear which tenant\'s or vendor\'s coverage applies in the event of a claim. Mixed-use properties also tend to have more complex ownership structures, with separate condo associations, retail LLCs, and management entities that all need to appear as additional insureds on vendor certificates. Tracking which entity should be named on which certificate is a compliance challenge that spreadsheet-based systems consistently fail to manage as the property scales.',
    commonCoverageGaps:
      'The most pervasive gap in mixed-use properties is inconsistent additional insured naming across use types. Vendors frequently name the management company but omit the retail LLC, condo association, or underlying property owner — leaving entities exposed to direct claims. Residential tenants in mixed-use buildings are less likely to maintain renters insurance than those in dedicated apartment communities because enforcement is often deprioritized behind commercial compliance. Restaurant tenants on ground floors regularly lack adequate liquor liability limits, and shared-area vendors like parking garage operators often carry auto liability below the minimums that mixed-use exposure demands.',
    howSmartCOIHelps:
      'SmartCOI\'s compliance templates let mixed-use property managers define separate requirement profiles for retail, office, and residential tenants within the same property. AI-powered extraction automatically verifies that all required entities are named as additional insureds, and the compliance dashboard provides a unified view across all use types — so nothing falls through the cracks between commercial and residential management workflows.',
  },
  {
    slug: 'medical-office-buildings',
    name: 'Medical Office Building',
    plural: 'Medical Office Buildings',
    description:
      'Medical offices, outpatient clinics, dental practices, and ambulatory surgery centers.',
    vendorExamples: ['biomedical waste disposal', 'medical equipment service', 'specialized cleaning', 'IT network contractors'],
    tenantExamples: ['physician practices', 'dental offices', 'physical therapy clinics', 'imaging centers'],
    complianceChallenges:
      'Medical office buildings operate at the intersection of property management and healthcare regulation, creating compliance requirements that go well beyond standard commercial insurance tracking. Clinical tenants — physician practices, surgical centers, imaging facilities — carry professional liability (malpractice) policies with complex coverage structures that differ significantly from the general liability certificates most property managers are trained to review. Verifying that a dermatology practice carries adequate per-claim and aggregate malpractice limits requires domain knowledge that standard COI review processes don\'t address. Vendors in medical buildings face heightened scrutiny as well. Biomedical waste haulers must carry pollution liability and specific regulatory endorsements. IT contractors accessing networks that store protected health information need cyber liability coverage — a requirement that is increasingly written into medical office leases but rarely tracked systematically. Even routine cleaning crews require specialized infection control training and higher liability limits than their counterparts in conventional office buildings, given the clinical environment and patient exposure. The consequences of a compliance lapse in a medical office building extend beyond financial loss. A vendor incident that disrupts clinical operations or compromises patient safety can trigger regulatory investigations, damage tenant relationships, and create liability exposure that standard commercial policies were never designed to cover.',
    commonCoverageGaps:
      'Professional liability verification is the most significant gap in medical office buildings. Property managers review ACORD 25 certificates for general liability but rarely verify the separate malpractice or professional liability policies that clinical leases require. Biomedical waste vendors frequently lack the pollution liability endorsement needed for regulated medical waste transport. IT contractors with access to networks handling electronic health records almost never carry cyber liability coverage unless specifically required. Medical equipment service vendors — working on MRI machines, X-ray systems, and surgical equipment — often carry inadequate professional liability for the specialized nature of their work.',
    howSmartCOIHelps:
      'SmartCOI\'s AI extraction reads beyond the standard ACORD 25 form to identify professional liability, pollution, and cyber coverage from multi-page certificate packages. Compliance templates tailored for medical office buildings enforce the higher limits and specialized endorsements that clinical environments require, and automated alerts ensure that no malpractice policy lapses go undetected between annual renewals.',
  },
  {
    slug: 'hospitality-hotels',
    name: 'Hospitality Property',
    plural: 'Hotels & Hospitality Properties',
    description:
      'Hotels, motels, resorts, and extended-stay properties with complex vendor relationships.',
    vendorExamples: ['linen services', 'food suppliers', 'valet parking', 'AV equipment providers'],
    tenantExamples: ['restaurant operators', 'spa operators', 'gift shop tenants', 'event planners'],
    complianceChallenges:
      'Hotels and hospitality properties manage more active vendor relationships than virtually any other commercial property type. A full-service hotel might work with 30-50 vendors at any given time — linen services, food and beverage suppliers, valet parking operators, AV equipment companies, pool maintenance crews, pest control, landscaping, and dozens of specialized contractors for everything from elevator repair to grease trap cleaning. The 24/7 nature of hotel operations means vendors access the property at all hours, often with minimal advance scheduling, making pre-arrival COI verification nearly impossible without an automated system. Event and banquet operations introduce an entirely separate layer of compliance complexity. Wedding planners, caterers, live entertainment acts, florists, and photography teams each require short-term certificates for single events, creating a constant flow of one-off COI requests that overwhelm manual tracking processes. Seasonal demand swings compound the problem — a resort property might triple its vendor count during peak season, bringing in temporary staffing agencies, additional food service vendors, and recreational activity operators who need coverage verified before their first shift. Hospitality properties also face unique tenant compliance challenges. Restaurant operators within hotels require liquor liability and food contamination coverage. Spa tenants need professional liability for treatment services. Gift shop operators carry product liability. Each tenant type requires a distinct compliance profile, and the high-visibility nature of hotel operations means that any incident — a guest injury, a food safety violation, a valet accident — becomes an immediate reputational and financial crisis.',
    commonCoverageGaps:
      'Liquor liability is the highest-risk gap in hospitality properties, particularly for hotel-operated bars and restaurant tenants. Many operators carry general liability without the separate liquor endorsement that hospitality leases should mandate. Valet parking operators frequently lack adequate garage-keepers liability and hired/non-owned auto coverage for the vehicles in their care. Event vendors — caterers, entertainers, decorators — routinely operate on expired or insufficient certificates because the urgency of event timelines discourages thorough verification. Temporary staffing agencies supplying housekeeping and banquet staff often carry workers\' compensation minimums that are inadequate for the physical demands of hospitality work.',
    howSmartCOIHelps:
      'SmartCOI handles the high vendor volume and rapid turnover that hospitality properties demand. Bulk upload processes dozens of vendor certificates at once, AI extraction automatically identifies liquor liability, garage-keepers coverage, and other hospitality-specific endorsements, and the self-service vendor portal lets event vendors and seasonal contractors submit certificates on their own timeline — keeping compliance current without slowing down hotel operations.',
  },
  {
    slug: 'self-storage-facilities',
    name: 'Self-Storage Facility',
    plural: 'Self-Storage Facilities',
    description:
      'Climate-controlled and standard self-storage facilities, including boat and RV storage.',
    vendorExamples: ['gate and access control repair', 'pest control', 'paving contractors', 'security system vendors'],
    tenantExamples: ['individual renters', 'small businesses', 'moving companies'],
    complianceChallenges:
      'Self-storage facilities present a deceptively complex compliance picture. While the vendor count is typically lower than in office or retail environments, the risk profile of storage operations creates insurance tracking challenges that are easy to underestimate. Gate and access control systems, security cameras, and climate control equipment all require specialized vendors whose coverage needs go beyond standard general liability. Paving and drainage contractors working on large surface lots need adequate auto liability for heavy equipment. Pest control vendors handling rodenticide and chemical treatments in enclosed storage units require pollution liability endorsements that many small operators don\'t carry. The tenant side of self-storage compliance is evolving rapidly. More facility operators now require tenant storage insurance — either through a facility-sponsored program or proof of personal coverage — but tracking compliance across hundreds or thousands of individual unit renters is operationally demanding. Small business tenants using storage units for inventory, equipment, or records have different coverage needs than individual renters, and moving companies operating out of storage facilities require commercial auto and cargo coverage that standard storage agreements rarely verify. Multi-site storage operators face the additional challenge of maintaining consistent compliance standards across geographically dispersed facilities, often managed by small on-site teams with limited insurance expertise.',
    commonCoverageGaps:
      'Tenant storage insurance verification is the most widespread gap in self-storage facilities. Many operators offer opt-in protection plans but don\'t systematically verify that tenants who decline actually maintain their own coverage, leaving the facility exposed to claims for water damage, theft, and pest damage. Moving company tenants operating commercial vehicles from the property frequently lack adequate commercial auto and cargo liability. Security system and access control vendors working with electrical systems often carry general liability but not the professional liability needed for system design failures. Climate control maintenance vendors servicing units with temperature-sensitive contents rarely carry the equipment breakdown coverage that would respond to a system failure damaging tenant property.',
    howSmartCOIHelps:
      'SmartCOI streamlines compliance tracking for self-storage operators managing certificates across multiple facilities and high volumes of unit renters. Automated expiration alerts catch lapsed tenant insurance before a claim occurs, compliance templates enforce facility-specific requirements for vendors, and the centralized dashboard gives multi-site operators visibility across their entire portfolio from a single screen.',
  },
];
